('Pet Carriers', 'Frame 86.png', 'Collapsible Dog Bow', 'Frame 86.png', 'Frame 86.png', 
    'Frame 86.png', 'Frame 86.png', 'S, M, L, XL', 10, 80.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
    'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
    'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
    'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
    'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
    'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
    'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),
    ('Cats', 'picture18.png', 'Breathable Cat Chest Straps', 'picture18.png', 'picture18.png', 
        'picture18.png', 'picture18.png', 'S, M, L, XL', 10, 190.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
        'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
        'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
        'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
        'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
        'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
        'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),
        ('Cats', 'picture1.png', 'Dogs Dress', 'picture1.png', 'picture1.png', 
            'picture1.png', 'picture1.png', 'S, M, L, XL', 10, 390.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
            'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
            'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
            'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
            'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
            'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
            'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),
    ('Dog & Cat Beds', 'picture2.png', 'Cats Beds', 'picture2.png', 'picture2.png', 
 'picture2.png', 'picture2.png', 'S, M, L, XL', 10, 290.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),('Cats', 'picture3.png', 'Breathable Cat Chest Straps', 'picture3.png', 'picture3.png', 
 'picture3.png', 'picture3.png', 'S, M, L, XL', 10, 190.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),('Dogs', 'picture4.png', 'Dogs Dress', 'picture4.png', 'picture4.png', 
 'picture4.png', 'picture4.png', 'S, M, L, XL', 10, 390.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),('Dogs', 'picture5.png', 'collapsible Dog Bow', 'picture5.png', 'picture5.png', 
 'picture5.png', 'picture5.png', 'S, M, L, XL', 10, 80.00, 3000.00,'2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),('Cats', 'picture6.png', 'Active pet cat harness', 'picture6.png', 'picture6.png', 
 'picture6.png', 'picture6.png', 'S, M, L, XL', 10, 90.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),('Dogs', 'picture7.png', 'embark adventure dog harness', 'picture7.png', 'picture7.png', 
 'picture7.png', 'picture7.png', 'S, M, L, XL', 10, 60.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),
 
 
 
 ('Dogs & Cats Beds', 'picture15.png', 'Cats Beds', 'picture15.png', 'picture15.png', 
 'picture15.png', 'picture15.png', 'S, M, L, XL', 10, 110.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),
 ('Pet Carriers', 'picture12.png', 'Non spill slow drink pet water bowl', 'picture12.png', 'picture12.png', 
 'picture12.png', 'picture12.png', 'S, M, L, XL', 10, 230.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),('Pet Carriers', 'picture14.png', 'pet slow food bowl', 'picture14.png', 'picture14.png', 
 'picture14.png', 'picture14.png', 'S, M, L, XL', 10, 130.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),('Pet Clothing', 'picture6.png', 'dog snowsuit', 'picture6.png', 'picture6.png', 
 'picture6.png', 'picture6.png', 'S, M, L, XL', 10, 180.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),('Dogs', 'picture11.png', 'dog car seat', 'picture11.png', 'picture11.png', 
 'picture11.png', 'picture11.png', 'S, M, L, XL', 10, 240.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),('Dog & Cat Beds', 'picture7.png', 'dog beds', 'picture7.png', 'picture7.png', 
 'picture7.png', 'picture7.png', 'S, M, L, XL', 10, 60.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),('Pet Clothing', 'picture10.png', 'dog life jacket', 'picture10.png', 'picture10.png', 
 'picture10.png', 'picture10.png', 'S, M, L, XL', 10, 280.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),('Pet Clothing', 'picture9.png', 'dog jacket', 'picture9.png', 'picture9.png', 
 'picture9.png', 'picture9.png', 'S, M, L, XL', 10, 280.00, 3000.00,'2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.'),('Pet Clothing', 'picture8.png', 'dog collar', 'picture8.png', 'picture8.png', 
 'picture9.png', 'picture8.png', 'S, M, L, XL', 10, 280.00, 3000.00, '2025-02-15', '2025-02-20', '10:00:00', '18:00:00', 
 'Made from soft, high-quality acrylic or wool blend, designed to keep your dog warm and comfortable in cold weather.', 
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.',
 'Warm and Cozy: Perfect for winter, keeping your dog snug and protected from the cold.', 'All products are made from durable, pet-friendly fabrics that are soft on your pet\'s skin and fur.', 'Easy to clean and maintain, durable for long-term use', 'Puppy, Adult, Senior', 
 'Our rental pet apparel, including sweaters, jackets, and harnesses, is designed to provide a snug and comfortable fit for dogs and cats of all sizes and breeds.', 
 'Dress your pet in trendy outfits perfect for any occasion, from cozy winter jackets to raincoats and breathable summer vests.', 
 'Lightweight and easy to wear, our accessories are designed for hassle-free use. All rental items are thoroughly cleaned and sanitized after each use. Protective Gear: Options like padded harnesses, reflective vests for night walks, and cooling vests for summer days. Seasonal Outfits: Christmas sweaters, Halloween costumes, or birthday hats. Bedding & Carriers: Soft, plush beds and easy-to-carry crates for travel or home use. Toys & Chewables: Variety of toys, from chew toys for teething puppies to interactive puzzles. Renting allows you to try different accessories without committing to a purchase.')





 const handleAddToCart = () => {
    const cartItem = {
      id: product.id,
      title: product.title,
      price: product.price,
      securityAmount: product.security_amount,
      size,
      quantity,
      pickupDate,
      dropoffDate,
      pickupTime,
      dropoffTime,
      color,
      image:
        color === 1
          ? product.image
          : color === 2
          ? product.color_image_orange
          : color === 3
          ? product.color_image_red
          : product.color_image_pink,
    };

    localStorage.setItem("cart", JSON.stringify(cartItem));
    console.log("Added to cart:", cartItem);
    // Navigate to checkout (adjust as needed)
    window.location.href = "/checkout";
  };